# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 208ae4a175f65662cf140e2d23864e9dd1f12778c40de655a6f4f548b864e9d0f74da9d593967c60fc754dda015b7a64c9e3001978eb375eb9a477d91522c243

test:
  secret_key_base: 31fcfc14a36372a2a5f2a53da99af7e0ba74b2f5463bed7d3334692aec096ed9a03313af94b0b5df4e4aa69119e200c9cd82a8c8f63fb1b7100a0a7ff69d6731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
